import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.scss']
})
export class UserFormComponent implements OnInit {
  userForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.userForm = this.fb.group({
      id: [''], // Autogenerated
      title: ['', Validators.required], // 'mr', 'ms', 'mrs', 'miss', 'dr', ''
      firstName: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(50)]],
      lastName: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(50)]],
      gender: ['', Validators.required], // 'male', 'female', 'other', ''
      email: ['', [Validators.required, Validators.email]],
      dateOfBirth: ['', [Validators.required, this.dateOfBirthValidator]],
      registerDate: [''], // Autogenerated
      phone: ['', [Validators.required, this.phoneValidator]],
      picture: ['', Validators.pattern('(http|https)://.+')] // URL pattern
    });
  }

  ngOnInit(): void {}

  dateOfBirthValidator(control: any) {
    const date = new Date(control.value);
    if (isNaN(date.getTime())) {
      return { invalidDateOfBirth: true };
    }
    return null;
  }

  phoneValidator(control: string) {
    // Add your phone number validation logic here
    return null; // Return null for valid phone numbers
  }

  onSubmit() {
    if (this.userForm.valid) {
      const formData = this.userForm.value;
      console.log(formData);
    }
  }
}
